#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP__ThrowingKnife_RotaTrailSteel_VE

#include "Basic.hpp"

#include "BP__ThrowingKnife_RotaTrailSteel_VE_classes.hpp"
#include "BP__ThrowingKnife_RotaTrailSteel_VE_parameters.hpp"


namespace SDK
{

// Function BP__ThrowingKnife_RotaTrailSteel_VE.BP__ThrowingKnife_RotaTrailSteel_VE_C.VisualEntityConstructionFinished
// (Event, Protected, BlueprintEvent)

void ABP__ThrowingKnife_RotaTrailSteel_VE_C::VisualEntityConstructionFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP__ThrowingKnife_RotaTrailSteel_VE_C", "VisualEntityConstructionFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP__ThrowingKnife_RotaTrailSteel_VE.BP__ThrowingKnife_RotaTrailSteel_VE_C.OnKill
// (Event, Protected, BlueprintEvent)

void ABP__ThrowingKnife_RotaTrailSteel_VE_C::OnKill()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP__ThrowingKnife_RotaTrailSteel_VE_C", "OnKill");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP__ThrowingKnife_RotaTrailSteel_VE.BP__ThrowingKnife_RotaTrailSteel_VE_C.ExecuteUbergraph_BP__ThrowingKnife_RotaTrailSteel_VE
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP__ThrowingKnife_RotaTrailSteel_VE_C::ExecuteUbergraph_BP__ThrowingKnife_RotaTrailSteel_VE(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP__ThrowingKnife_RotaTrailSteel_VE_C", "ExecuteUbergraph_BP__ThrowingKnife_RotaTrailSteel_VE");

	Params::BP__ThrowingKnife_RotaTrailSteel_VE_C_ExecuteUbergraph_BP__ThrowingKnife_RotaTrailSteel_VE Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

