#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArbitersFuryCharge_VE

#include "Basic.hpp"

#include "BP_ArbitersFuryCharge_VE_classes.hpp"
#include "BP_ArbitersFuryCharge_VE_parameters.hpp"


namespace SDK
{

// Function BP_ArbitersFuryCharge_VE.BP_ArbitersFuryCharge_VE_C.ExecuteUbergraph_BP_ArbitersFuryCharge_VE
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ArbitersFuryCharge_VE_C::ExecuteUbergraph_BP_ArbitersFuryCharge_VE(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArbitersFuryCharge_VE_C", "ExecuteUbergraph_BP_ArbitersFuryCharge_VE");

	Params::BP_ArbitersFuryCharge_VE_C_ExecuteUbergraph_BP_ArbitersFuryCharge_VE Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArbitersFuryCharge_VE.BP_ArbitersFuryCharge_VE_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ArbitersFuryCharge_VE_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArbitersFuryCharge_VE_C", "ReceiveTick");

	Params::BP_ArbitersFuryCharge_VE_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArbitersFuryCharge_VE.BP_ArbitersFuryCharge_VE_C.VisualEntityConstructionFinished
// (Event, Protected, BlueprintEvent)

void ABP_ArbitersFuryCharge_VE_C::VisualEntityConstructionFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArbitersFuryCharge_VE_C", "VisualEntityConstructionFinished");

	UObject::ProcessEvent(Func, nullptr);
}

}

