#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BladeDance_ActiveAbility

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BladeDance_ActiveAbility.BP_BladeDance_ActiveAbility_C
// 0x0000 (0x0610 - 0x0610)
class UBP_BladeDance_ActiveAbility_C final : public UBladeDanceAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BladeDance_ActiveAbility_C">();
	}
	static class UBP_BladeDance_ActiveAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BladeDance_ActiveAbility_C>();
	}
};
static_assert(alignof(UBP_BladeDance_ActiveAbility_C) == 0x000008, "Wrong alignment on UBP_BladeDance_ActiveAbility_C");
static_assert(sizeof(UBP_BladeDance_ActiveAbility_C) == 0x000610, "Wrong size on UBP_BladeDance_ActiveAbility_C");

}

