#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Brawler_SpeechBubbleControl

#include "Basic.hpp"

#include "BP_Brawler_SpeechBubbleControl_classes.hpp"
#include "BP_Brawler_SpeechBubbleControl_parameters.hpp"


namespace SDK
{

// Function BP_Brawler_SpeechBubbleControl.BP_Brawler_SpeechBubbleControl_C.ExecuteUbergraph_BP_Brawler_SpeechBubbleControl
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Brawler_SpeechBubbleControl_C::ExecuteUbergraph_BP_Brawler_SpeechBubbleControl(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Brawler_SpeechBubbleControl_C", "ExecuteUbergraph_BP_Brawler_SpeechBubbleControl");

	Params::BP_Brawler_SpeechBubbleControl_C_ExecuteUbergraph_BP_Brawler_SpeechBubbleControl Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Brawler_SpeechBubbleControl.BP_Brawler_SpeechBubbleControl_C.OnStatusEffectChange
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EStatusEffectChange                     Change                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EStatusEffectType                       StatusType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           SourceEntity                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   StackNum_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Brawler_SpeechBubbleControl_C::OnStatusEffectChange(EStatusEffectChange Change, EStatusEffectType StatusType, class AActor* SourceEntity, int32 StackNum_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Brawler_SpeechBubbleControl_C", "OnStatusEffectChange");

	Params::BP_Brawler_SpeechBubbleControl_C_OnStatusEffectChange Parms{};

	Parms.Change = Change;
	Parms.StatusType = StatusType;
	Parms.SourceEntity = SourceEntity;
	Parms.StackNum_0 = StackNum_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Brawler_SpeechBubbleControl.BP_Brawler_SpeechBubbleControl_C.TrapDamage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilityController*               Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAbilityController*               Bullet                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAbilityController*               Target_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAbilityBase*                     Ability                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   effectiveDamage                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FDamageValue                     DamageValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)

void UBP_Brawler_SpeechBubbleControl_C::TrapDamage(class UAbilityController* Source, class UAbilityController* Bullet, class UAbilityController* Target_0, class UAbilityBase* Ability, float effectiveDamage, const struct FDamageValue& DamageValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Brawler_SpeechBubbleControl_C", "TrapDamage");

	Params::BP_Brawler_SpeechBubbleControl_C_TrapDamage Parms{};

	Parms.Source = Source;
	Parms.Bullet = Bullet;
	Parms.Target_0 = Target_0;
	Parms.Ability = Ability;
	Parms.effectiveDamage = effectiveDamage;
	Parms.DamageValue = std::move(DamageValue);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Brawler_SpeechBubbleControl.BP_Brawler_SpeechBubbleControl_C.BPOnStart
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_Brawler_SpeechBubbleControl_C::BPOnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Brawler_SpeechBubbleControl_C", "BPOnStart");

	UObject::ProcessEvent(Func, nullptr);
}

}

