#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Brawler_SpeechBubbleControl

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Brawler_SpeechBubbleControl.BP_Brawler_SpeechBubbleControl_C
// 0x0008 (0x0638 - 0x0630)
class UBP_Brawler_SpeechBubbleControl_C final : public UEmptyPassiveAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0630(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Brawler_SpeechBubbleControl(int32 EntryPoint);
	void OnStatusEffectChange(EStatusEffectChange Change, EStatusEffectType StatusType, class AActor* SourceEntity, int32 StackNum_0);
	void TrapDamage(class UAbilityController* Source, class UAbilityController* Bullet, class UAbilityController* Target_0, class UAbilityBase* Ability, float effectiveDamage, const struct FDamageValue& DamageValue);
	void BPOnStart();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Brawler_SpeechBubbleControl_C">();
	}
	static class UBP_Brawler_SpeechBubbleControl_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Brawler_SpeechBubbleControl_C>();
	}
};
static_assert(alignof(UBP_Brawler_SpeechBubbleControl_C) == 0x000008, "Wrong alignment on UBP_Brawler_SpeechBubbleControl_C");
static_assert(sizeof(UBP_Brawler_SpeechBubbleControl_C) == 0x000638, "Wrong size on UBP_Brawler_SpeechBubbleControl_C");
static_assert(offsetof(UBP_Brawler_SpeechBubbleControl_C, UberGraphFrame) == 0x000630, "Member 'UBP_Brawler_SpeechBubbleControl_C::UberGraphFrame' has a wrong offset!");

}

