#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Credits_BackersList

#include "Basic.hpp"

#include "BP_Credits_BackersList_classes.hpp"
#include "BP_Credits_BackersList_parameters.hpp"


namespace SDK
{

// Function BP_Credits_BackersList.BP_Credits_BackersList_C.ExecuteUbergraph_BP_Credits_BackersList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Credits_BackersList_C::ExecuteUbergraph_BP_Credits_BackersList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Credits_BackersList_C", "ExecuteUbergraph_BP_Credits_BackersList");

	Params::BP_Credits_BackersList_C_ExecuteUbergraph_BP_Credits_BackersList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Credits_BackersList.BP_Credits_BackersList_C.OnSetText
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             InLeftText                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             InCenterText                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             InRightText                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_Credits_BackersList_C::OnSetText(const class FText& InLeftText, const class FText& InCenterText, const class FText& InRightText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Credits_BackersList_C", "OnSetText");

	Params::BP_Credits_BackersList_C_OnSetText Parms{};

	Parms.InLeftText = std::move(InLeftText);
	Parms.InCenterText = std::move(InCenterText);
	Parms.InRightText = std::move(InRightText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Credits_BackersList.BP_Credits_BackersList_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Credits_BackersList_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Credits_BackersList_C", "PreConstruct");

	Params::BP_Credits_BackersList_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Credits_BackersList.BP_Credits_BackersList_C.SetTexts
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InCol1                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             InCol2                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             InCol3                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_Credits_BackersList_C::SetTexts(const class FText& InCol1, const class FText& InCol2, const class FText& InCol3)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Credits_BackersList_C", "SetTexts");

	Params::BP_Credits_BackersList_C_SetTexts Parms{};

	Parms.InCol1 = std::move(InCol1);
	Parms.InCol2 = std::move(InCol2);
	Parms.InCol3 = std::move(InCol3);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Credits_BackersList.BP_Credits_BackersList_C.ToggleSmallScreen
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIsSmallScreen                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Credits_BackersList_C::ToggleSmallScreen(bool InIsSmallScreen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Credits_BackersList_C", "ToggleSmallScreen");

	Params::BP_Credits_BackersList_C_ToggleSmallScreen Parms{};

	Parms.InIsSmallScreen = InIsSmallScreen;

	UObject::ProcessEvent(Func, &Parms);
}

}

