#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Collection_ItemsHandler

#include "Basic.hpp"

#include "BP_Collection_ItemsHandler_classes.hpp"
#include "BP_Collection_ItemsHandler_parameters.hpp"


namespace SDK
{

// Function BP_Collection_ItemsHandler.BP_Collection_ItemsHandler_C.ExecuteUbergraph_BP_Collection_ItemsHandler
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Collection_ItemsHandler_C::ExecuteUbergraph_BP_Collection_ItemsHandler(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Collection_ItemsHandler_C", "ExecuteUbergraph_BP_Collection_ItemsHandler");

	Params::BP_Collection_ItemsHandler_C_ExecuteUbergraph_BP_Collection_ItemsHandler Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Collection_ItemsHandler.BP_Collection_ItemsHandler_C.UpdateDetailsPanel
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             ItemRequirementText                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UItemAbility*                     Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemAbility*                     ComparedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bEquipped                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bAnimate                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bHighlightTooltip                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Collection_ItemsHandler_C::UpdateDetailsPanel(const class FText& ItemRequirementText, class UItemAbility* Item, class UItemAbility* ComparedItem, bool bEquipped, bool bAnimate, bool bHighlightTooltip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Collection_ItemsHandler_C", "UpdateDetailsPanel");

	Params::BP_Collection_ItemsHandler_C_UpdateDetailsPanel Parms{};

	Parms.ItemRequirementText = std::move(ItemRequirementText);
	Parms.Item = Item;
	Parms.ComparedItem = ComparedItem;
	Parms.bEquipped = bEquipped;
	Parms.bAnimate = bAnimate;
	Parms.bHighlightTooltip = bHighlightTooltip;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Collection_ItemsHandler.BP_Collection_ItemsHandler_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Collection_ItemsHandler_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Collection_ItemsHandler_C", "PreConstruct");

	Params::BP_Collection_ItemsHandler_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Collection_ItemsHandler.BP_Collection_ItemsHandler_C.ToggleSmallScreen
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIsSmallScreen                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Collection_ItemsHandler_C::ToggleSmallScreen(bool InIsSmallScreen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Collection_ItemsHandler_C", "ToggleSmallScreen");

	Params::BP_Collection_ItemsHandler_C_ToggleSmallScreen Parms{};

	Parms.InIsSmallScreen = InIsSmallScreen;

	UObject::ProcessEvent(Func, &Parms);
}

}

