#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChanneledChaosVortex_ActiveAbility

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ChanneledChaosVortex_ActiveAbility.BP_ChanneledChaosVortex_ActiveAbility_C
// 0x0000 (0x08E0 - 0x08E0)
class UBP_ChanneledChaosVortex_ActiveAbility_C final : public UChaosVortexAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ChanneledChaosVortex_ActiveAbility_C">();
	}
	static class UBP_ChanneledChaosVortex_ActiveAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ChanneledChaosVortex_ActiveAbility_C>();
	}
};
static_assert(alignof(UBP_ChanneledChaosVortex_ActiveAbility_C) == 0x000008, "Wrong alignment on UBP_ChanneledChaosVortex_ActiveAbility_C");
static_assert(sizeof(UBP_ChanneledChaosVortex_ActiveAbility_C) == 0x0008E0, "Wrong size on UBP_ChanneledChaosVortex_ActiveAbility_C");

}

