#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CasterImp

#include "Basic.hpp"

#include "BP_CasterImp_classes.hpp"
#include "BP_CasterImp_parameters.hpp"


namespace SDK
{

// Function BP_CasterImp.BP_CasterImp_C.ExecuteUbergraph_BP_CasterImp
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CasterImp_C::ExecuteUbergraph_BP_CasterImp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CasterImp_C", "ExecuteUbergraph_BP_CasterImp");

	Params::BP_CasterImp_C_ExecuteUbergraph_BP_CasterImp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CasterImp.BP_CasterImp_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CasterImp_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CasterImp_C", "ReceiveTick");

	Params::BP_CasterImp_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CasterImp.BP_CasterImp_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CasterImp_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CasterImp_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CasterImp.BP_CasterImp_C.OnKilled_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Killer                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAbilityController*               KillerAbilityController                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CasterImp_C::OnKilled_Event_0(class UObject* Killer, class UAbilityController* KillerAbilityController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CasterImp_C", "OnKilled_Event_0");

	Params::BP_CasterImp_C_OnKilled_Event_0 Parms{};

	Parms.Killer = Killer;
	Parms.KillerAbilityController = KillerAbilityController;

	UObject::ProcessEvent(Func, &Parms);
}

}

