#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChaosBeam_ActiveAbility

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ChaosBeam_ActiveAbility.BP_ChaosBeam_ActiveAbility_C
// 0x0000 (0x0EB0 - 0x0EB0)
class UBP_ChaosBeam_ActiveAbility_C final : public UBeamAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ChaosBeam_ActiveAbility_C">();
	}
	static class UBP_ChaosBeam_ActiveAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ChaosBeam_ActiveAbility_C>();
	}
};
static_assert(alignof(UBP_ChaosBeam_ActiveAbility_C) == 0x000008, "Wrong alignment on UBP_ChaosBeam_ActiveAbility_C");
static_assert(sizeof(UBP_ChaosBeam_ActiveAbility_C) == 0x000EB0, "Wrong size on UBP_ChaosBeam_ActiveAbility_C");

}

