#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ConsecrationVisualEntity

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ConsecrationVisualEntity.BP_ConsecrationVisualEntity_C
// 0x0010 (0x0360 - 0x0350)
class ABP_ConsecrationVisualEntity_C final : public AVisualEntity
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara;                                           // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ConsecrationVisualEntity(int32 EntryPoint);
	void VisualEntityConstructionFinished();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ConsecrationVisualEntity_C">();
	}
	static class ABP_ConsecrationVisualEntity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ConsecrationVisualEntity_C>();
	}
};
static_assert(alignof(ABP_ConsecrationVisualEntity_C) == 0x000008, "Wrong alignment on ABP_ConsecrationVisualEntity_C");
static_assert(sizeof(ABP_ConsecrationVisualEntity_C) == 0x000360, "Wrong size on ABP_ConsecrationVisualEntity_C");
static_assert(offsetof(ABP_ConsecrationVisualEntity_C, UberGraphFrame) == 0x000350, "Member 'ABP_ConsecrationVisualEntity_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_ConsecrationVisualEntity_C, Niagara) == 0x000358, "Member 'ABP_ConsecrationVisualEntity_C::Niagara' has a wrong offset!");

}

