#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DieOfChaos_ActiveAbility

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DieOfChaos_ActiveAbility.BP_DieOfChaos_ActiveAbility_C
// 0x0000 (0x0848 - 0x0848)
class UBP_DieOfChaos_ActiveAbility_C final : public UDieOfChaosAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DieOfChaos_ActiveAbility_C">();
	}
	static class UBP_DieOfChaos_ActiveAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DieOfChaos_ActiveAbility_C>();
	}
};
static_assert(alignof(UBP_DieOfChaos_ActiveAbility_C) == 0x000008, "Wrong alignment on UBP_DieOfChaos_ActiveAbility_C");
static_assert(sizeof(UBP_DieOfChaos_ActiveAbility_C) == 0x000848, "Wrong size on UBP_DieOfChaos_ActiveAbility_C");

}

