#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DarkEcho_ActiveAbility

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DarkEcho_ActiveAbility.BP_DarkEcho_ActiveAbility_C
// 0x0010 (0x07A0 - 0x0790)
class UBP_DarkEcho_ActiveAbility_C final : public UTeleportBackOnTriggerAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0790(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_DarkEcho_Explosion_VisualEntity_C*  VE;                                                // 0x0798(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DarkEcho_ActiveAbility(int32 EntryPoint);
	void BPAbilityCustomEvent(class FName CustomName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DarkEcho_ActiveAbility_C">();
	}
	static class UBP_DarkEcho_ActiveAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DarkEcho_ActiveAbility_C>();
	}
};
static_assert(alignof(UBP_DarkEcho_ActiveAbility_C) == 0x000008, "Wrong alignment on UBP_DarkEcho_ActiveAbility_C");
static_assert(sizeof(UBP_DarkEcho_ActiveAbility_C) == 0x0007A0, "Wrong size on UBP_DarkEcho_ActiveAbility_C");
static_assert(offsetof(UBP_DarkEcho_ActiveAbility_C, UberGraphFrame) == 0x000790, "Member 'UBP_DarkEcho_ActiveAbility_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_DarkEcho_ActiveAbility_C, VE) == 0x000798, "Member 'UBP_DarkEcho_ActiveAbility_C::VE' has a wrong offset!");

}

