#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DefaultCursor

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_DefaultCursor.BP_DefaultCursor_C
// 0x0008 (0x0268 - 0x0260)
class UBP_DefaultCursor_C final : public UUserWidget
{
public:
	class UImage*                                 Image_0;                                           // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DefaultCursor_C">();
	}
	static class UBP_DefaultCursor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DefaultCursor_C>();
	}
};
static_assert(alignof(UBP_DefaultCursor_C) == 0x000008, "Wrong alignment on UBP_DefaultCursor_C");
static_assert(sizeof(UBP_DefaultCursor_C) == 0x000268, "Wrong size on UBP_DefaultCursor_C");
static_assert(offsetof(UBP_DefaultCursor_C, Image_0) == 0x000260, "Member 'UBP_DefaultCursor_C::Image_0' has a wrong offset!");

}

