#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Door_ActorBase

#include "Basic.hpp"

#include "BP_Door_ActorBase_classes.hpp"
#include "BP_Door_ActorBase_parameters.hpp"


namespace SDK
{

// Function BP_Door_ActorBase.BP_Door_ActorBase_C.StartOpened
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Door_ActorBase_C::StartOpened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "StartOpened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.CloseDoor
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Door_ActorBase_C::CloseDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "CloseDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.OpenDoor
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Door_ActorBase_C::OpenDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "OpenDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Door_ActorBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_Door_ActorBase_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_Door_ActorBase_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.BPPostBeginPlay
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Door_ActorBase_C::BPPostBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "BPPostBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.OnBPStart
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAbilityBase*                     InAbility                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Door_ActorBase_C::OnBPStart(class UAbilityBase* InAbility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "OnBPStart");

	Params::BP_Door_ActorBase_C_OnBPStart Parms{};

	Parms.InAbility = InAbility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.OnVfxEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             VfxEventType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Door_ActorBase_C::OnVfxEvent(class FName VfxEventType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "OnVfxEvent");

	Params::BP_Door_ActorBase_C_OnVfxEvent Parms{};

	Parms.VfxEventType = VfxEventType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Door_ActorBase.BP_Door_ActorBase_C.ExecuteUbergraph_BP_Door_ActorBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Door_ActorBase_C::ExecuteUbergraph_BP_Door_ActorBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_ActorBase_C", "ExecuteUbergraph_BP_Door_ActorBase");

	Params::BP_Door_ActorBase_C_ExecuteUbergraph_BP_Door_ActorBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

