#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DeathEssence_OnInteract

#include "Basic.hpp"

#include "BP_DeathEssence_OnInteract_classes.hpp"
#include "BP_DeathEssence_OnInteract_parameters.hpp"


namespace SDK
{

// Function BP_DeathEssence_OnInteract.BP_DeathEssence_OnInteract_C.ExecuteUbergraph_BP_DeathEssence_OnInteract
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_DeathEssence_OnInteract_C::ExecuteUbergraph_BP_DeathEssence_OnInteract(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeathEssence_OnInteract_C", "ExecuteUbergraph_BP_DeathEssence_OnInteract");

	Params::BP_DeathEssence_OnInteract_C_ExecuteUbergraph_BP_DeathEssence_OnInteract Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DeathEssence_OnInteract.BP_DeathEssence_OnInteract_C.BPOnStart
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_DeathEssence_OnInteract_C::BPOnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DeathEssence_OnInteract_C", "BPOnStart");

	UObject::ProcessEvent(Func, nullptr);
}

}

