#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EvadedText

#include "Basic.hpp"

#include "BP_EvadedText_classes.hpp"
#include "BP_EvadedText_parameters.hpp"


namespace SDK
{

// Function BP_EvadedText.BP_EvadedText_C.ExecuteUbergraph_BP_EvadedText
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EvadedText_C::ExecuteUbergraph_BP_EvadedText(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvadedText_C", "ExecuteUbergraph_BP_EvadedText");

	Params::BP_EvadedText_C_ExecuteUbergraph_BP_EvadedText Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EvadedText.BP_EvadedText_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EvadedText_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvadedText_C", "ReceiveTick");

	Params::BP_EvadedText_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

