#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Egg_ItemAbility

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Egg_ItemAbility.BP_Egg_ItemAbility_C
// 0x0000 (0x07F0 - 0x07F0)
class UBP_Egg_ItemAbility_C final : public UItemAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Egg_ItemAbility_C">();
	}
	static class UBP_Egg_ItemAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Egg_ItemAbility_C>();
	}
};
static_assert(alignof(UBP_Egg_ItemAbility_C) == 0x000008, "Wrong alignment on UBP_Egg_ItemAbility_C");
static_assert(sizeof(UBP_Egg_ItemAbility_C) == 0x0007F0, "Wrong size on UBP_Egg_ItemAbility_C");

}

