#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FlaskNumberUpgraded

#include "Basic.hpp"

#include "BP_FlaskNumberUpgraded_classes.hpp"
#include "BP_FlaskNumberUpgraded_parameters.hpp"


namespace SDK
{

// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.ExecuteUbergraph_BP_FlaskNumberUpgraded
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FlaskNumberUpgraded_C::ExecuteUbergraph_BP_FlaskNumberUpgraded(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "ExecuteUbergraph_BP_FlaskNumberUpgraded");

	Params::BP_FlaskNumberUpgraded_C_ExecuteUbergraph_BP_FlaskNumberUpgraded Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_FlaskNumberUpgraded_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "PreConstruct");

	Params::BP_FlaskNumberUpgraded_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.OnSetData
// (Event, Protected, BlueprintEvent)
// Parameters:
// struct FHUDPopupQueue                   InHUDPopupQueue                                        (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_FlaskNumberUpgraded_C::OnSetData(const struct FHUDPopupQueue& InHUDPopupQueue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "OnSetData");

	Params::BP_FlaskNumberUpgraded_C_OnSetData Parms{};

	Parms.InHUDPopupQueue = std::move(InHUDPopupQueue);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.OnShow
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AnimDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FlaskNumberUpgraded_C::OnShow(float AnimDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "OnShow");

	Params::BP_FlaskNumberUpgraded_C_OnShow Parms{};

	Parms.AnimDuration = AnimDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.OnHide
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AnimDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FlaskNumberUpgraded_C::OnHide(float AnimDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "OnHide");

	Params::BP_FlaskNumberUpgraded_C_OnHide Parms{};

	Parms.AnimDuration = AnimDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FlaskNumberUpgraded_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "Tick");

	Params::BP_FlaskNumberUpgraded_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_FlaskNumberUpgraded_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FlaskNumberUpgraded.BP_FlaskNumberUpgraded_C.SetData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Icon                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FlaskNumberUpgraded_C::SetData(class UTexture2D* Icon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FlaskNumberUpgraded_C", "SetData");

	Params::BP_FlaskNumberUpgraded_C_SetData Parms{};

	Parms.Icon = Icon;

	UObject::ProcessEvent(Func, &Parms);
}

}

