#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Flask_Base

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Flask_Base.BP_Flask_Base_C
// 0x0008 (0x0810 - 0x0808)
class UBP_Flask_Base_C : public UFlaskItemAbility
{
public:
	float                                         DrinkTime;                                         // 0x0808(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         StartLoopTime;                                     // 0x080C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Flask_Base_C">();
	}
	static class UBP_Flask_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Flask_Base_C>();
	}
};
static_assert(alignof(UBP_Flask_Base_C) == 0x000008, "Wrong alignment on UBP_Flask_Base_C");
static_assert(sizeof(UBP_Flask_Base_C) == 0x000810, "Wrong size on UBP_Flask_Base_C");
static_assert(offsetof(UBP_Flask_Base_C, DrinkTime) == 0x000808, "Member 'UBP_Flask_Base_C::DrinkTime' has a wrong offset!");
static_assert(offsetof(UBP_Flask_Base_C, StartLoopTime) == 0x00080C, "Member 'UBP_Flask_Base_C::StartLoopTime' has a wrong offset!");

}

