#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Frock_ItemAbility

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Frock_ItemAbility.BP_Frock_ItemAbility_C
// 0x0000 (0x07F0 - 0x07F0)
class UBP_Frock_ItemAbility_C final : public UItemAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Frock_ItemAbility_C">();
	}
	static class UBP_Frock_ItemAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Frock_ItemAbility_C>();
	}
};
static_assert(alignof(UBP_Frock_ItemAbility_C) == 0x000008, "Wrong alignment on UBP_Frock_ItemAbility_C");
static_assert(sizeof(UBP_Frock_ItemAbility_C) == 0x0007F0, "Wrong size on UBP_Frock_ItemAbility_C");

}

