#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GeneralLightBrandStatusEffect

#include "Basic.hpp"

#include "BP_GeneralLightBrandStatusEffect_classes.hpp"
#include "BP_GeneralLightBrandStatusEffect_parameters.hpp"


namespace SDK
{

// Function BP_GeneralLightBrandStatusEffect.BP_GeneralLightBrandStatusEffect_C.ExecuteUbergraph_BP_GeneralLightBrandStatusEffect
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GeneralLightBrandStatusEffect_C::ExecuteUbergraph_BP_GeneralLightBrandStatusEffect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GeneralLightBrandStatusEffect_C", "ExecuteUbergraph_BP_GeneralLightBrandStatusEffect");

	Params::BP_GeneralLightBrandStatusEffect_C_ExecuteUbergraph_BP_GeneralLightBrandStatusEffect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GeneralLightBrandStatusEffect.BP_GeneralLightBrandStatusEffect_C.BPAbilityCustomEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             CustomName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GeneralLightBrandStatusEffect_C::BPAbilityCustomEvent(class FName CustomName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GeneralLightBrandStatusEffect_C", "BPAbilityCustomEvent");

	Params::BP_GeneralLightBrandStatusEffect_C_BPAbilityCustomEvent Parms{};

	Parms.CustomName = CustomName;

	UObject::ProcessEvent(Func, &Parms);
}

}

