#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GoldsmithNPC

#include "Basic.hpp"

#include "BP_GoldsmithNPC_classes.hpp"
#include "BP_GoldsmithNPC_parameters.hpp"


namespace SDK
{

// Function BP_GoldsmithNPC.BP_GoldsmithNPC_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_GoldsmithNPC_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GoldsmithNPC_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GoldsmithNPC.BP_GoldsmithNPC_C.VisualVolumeEnter
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALevelVisualVolume*               Volume                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GoldsmithNPC_C::VisualVolumeEnter(class ALevelVisualVolume* Volume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GoldsmithNPC_C", "VisualVolumeEnter");

	Params::BP_GoldsmithNPC_C_VisualVolumeEnter Parms{};

	Parms.Volume = Volume;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GoldsmithNPC.BP_GoldsmithNPC_C.ExecuteUbergraph_BP_GoldsmithNPC
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GoldsmithNPC_C::ExecuteUbergraph_BP_GoldsmithNPC(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GoldsmithNPC_C", "ExecuteUbergraph_BP_GoldsmithNPC");

	Params::BP_GoldsmithNPC_C_ExecuteUbergraph_BP_GoldsmithNPC Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

