#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HUD_KeyItemSlot

#include "Basic.hpp"

#include "BP_HUD_KeyItemSlot_classes.hpp"
#include "BP_HUD_KeyItemSlot_parameters.hpp"


namespace SDK
{

// Function BP_HUD_KeyItemSlot.BP_HUD_KeyItemSlot_C.ExecuteUbergraph_BP_HUD_KeyItemSlot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HUD_KeyItemSlot_C::ExecuteUbergraph_BP_HUD_KeyItemSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_KeyItemSlot_C", "ExecuteUbergraph_BP_HUD_KeyItemSlot");

	Params::BP_HUD_KeyItemSlot_C_ExecuteUbergraph_BP_HUD_KeyItemSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HUD_KeyItemSlot.BP_HUD_KeyItemSlot_C.OnPlayHighlight
// (Event, Public, BlueprintEvent)

void UBP_HUD_KeyItemSlot_C::OnPlayHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_KeyItemSlot_C", "OnPlayHighlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HUD_KeyItemSlot.BP_HUD_KeyItemSlot_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HUD_KeyItemSlot_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_KeyItemSlot_C", "Tick");

	Params::BP_HUD_KeyItemSlot_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HUD_KeyItemSlot.BP_HUD_KeyItemSlot_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HUD_KeyItemSlot_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_KeyItemSlot_C", "PreConstruct");

	Params::BP_HUD_KeyItemSlot_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HUD_KeyItemSlot.BP_HUD_KeyItemSlot_C.SetIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       InIcon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HUD_KeyItemSlot_C::SetIcon(class UTexture2D* InIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_KeyItemSlot_C", "SetIcon");

	Params::BP_HUD_KeyItemSlot_C_SetIcon Parms{};

	Parms.InIcon = InIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HUD_KeyItemSlot.BP_HUD_KeyItemSlot_C.PlayHighlight
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_HUD_KeyItemSlot_C::PlayHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_KeyItemSlot_C", "PlayHighlight");

	UObject::ProcessEvent(Func, nullptr);
}

}

