#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractiveDoor_Anim

#include "Basic.hpp"

#include "BP_InteractiveDoor_Anim_classes.hpp"
#include "BP_InteractiveDoor_Anim_parameters.hpp"


namespace SDK
{

// Function BP_InteractiveDoor_Anim.BP_InteractiveDoor_Anim_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UBP_InteractiveDoor_Anim_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveDoor_Anim_C", "AnimGraph");

	Params::BP_InteractiveDoor_Anim_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function BP_InteractiveDoor_Anim.BP_InteractiveDoor_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_InteractiveDoor_Anim_AnimGraphNode_MirrorBones_D64A3B9E46F12C6F3C994394BE1F754C
// (BlueprintEvent)

void UBP_InteractiveDoor_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_InteractiveDoor_Anim_AnimGraphNode_MirrorBones_D64A3B9E46F12C6F3C994394BE1F754C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveDoor_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_InteractiveDoor_Anim_AnimGraphNode_MirrorBones_D64A3B9E46F12C6F3C994394BE1F754C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractiveDoor_Anim.BP_InteractiveDoor_Anim_C.OnAnimStartRequest
// (Event, Public, BlueprintEvent)
// Parameters:
// class UAnimID*                          AnimID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InteractiveDoor_Anim_C::OnAnimStartRequest(class UAnimID* AnimID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveDoor_Anim_C", "OnAnimStartRequest");

	Params::BP_InteractiveDoor_Anim_C_OnAnimStartRequest Parms{};

	Parms.AnimID = AnimID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractiveDoor_Anim.BP_InteractiveDoor_Anim_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UBP_InteractiveDoor_Anim_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveDoor_Anim_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractiveDoor_Anim.BP_InteractiveDoor_Anim_C.BlueprintBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_InteractiveDoor_Anim_C::BlueprintBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveDoor_Anim_C", "BlueprintBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractiveDoor_Anim.BP_InteractiveDoor_Anim_C.ExecuteUbergraph_BP_InteractiveDoor_Anim
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InteractiveDoor_Anim_C::ExecuteUbergraph_BP_InteractiveDoor_Anim(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveDoor_Anim_C", "ExecuteUbergraph_BP_InteractiveDoor_Anim");

	Params::BP_InteractiveDoor_Anim_C_ExecuteUbergraph_BP_InteractiveDoor_Anim Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

