#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LibrarianBookPageProjectile

#include "Basic.hpp"

#include "BP_LibrarianBookPageProjectile_classes.hpp"
#include "BP_LibrarianBookPageProjectile_parameters.hpp"


namespace SDK
{

// Function BP_LibrarianBookPageProjectile.BP_LibrarianBookPageProjectile_C.ExecuteUbergraph_BP_LibrarianBookPageProjectile
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LibrarianBookPageProjectile_C::ExecuteUbergraph_BP_LibrarianBookPageProjectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LibrarianBookPageProjectile_C", "ExecuteUbergraph_BP_LibrarianBookPageProjectile");

	Params::BP_LibrarianBookPageProjectile_C_ExecuteUbergraph_BP_LibrarianBookPageProjectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LibrarianBookPageProjectile.BP_LibrarianBookPageProjectile_C.BPPostBeginPlay
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_LibrarianBookPageProjectile_C::BPPostBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LibrarianBookPageProjectile_C", "BPPostBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

