#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LibrarianFastLearnerBurnBookActorAbility

#include "Basic.hpp"

#include "BP_LibrarianFastLearnerBookActorAbility_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LibrarianFastLearnerBurnBookActorAbility.BP_LibrarianFastLearnerBurnBookActorAbility_C
// 0x0000 (0x0658 - 0x0658)
class UBP_LibrarianFastLearnerBurnBookActorAbility_C final : public UBP_LibrarianFastLearnerBookActorAbility_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LibrarianFastLearnerBurnBookActorAbility_C">();
	}
	static class UBP_LibrarianFastLearnerBurnBookActorAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LibrarianFastLearnerBurnBookActorAbility_C>();
	}
};
static_assert(alignof(UBP_LibrarianFastLearnerBurnBookActorAbility_C) == 0x000008, "Wrong alignment on UBP_LibrarianFastLearnerBurnBookActorAbility_C");
static_assert(sizeof(UBP_LibrarianFastLearnerBurnBookActorAbility_C) == 0x000658, "Wrong size on UBP_LibrarianFastLearnerBurnBookActorAbility_C");

}

