#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LibrarianBookOfEnlightenment

#include "Basic.hpp"

#include "BP_LibrarianBookOfEnlightenment_classes.hpp"
#include "BP_LibrarianBookOfEnlightenment_parameters.hpp"


namespace SDK
{

// Function BP_LibrarianBookOfEnlightenment.BP_LibrarianBookOfEnlightenment_C.ExecuteUbergraph_BP_LibrarianBookOfEnlightenment
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_LibrarianBookOfEnlightenment_C::ExecuteUbergraph_BP_LibrarianBookOfEnlightenment(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LibrarianBookOfEnlightenment_C", "ExecuteUbergraph_BP_LibrarianBookOfEnlightenment");

	Params::BP_LibrarianBookOfEnlightenment_C_ExecuteUbergraph_BP_LibrarianBookOfEnlightenment Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LibrarianBookOfEnlightenment.BP_LibrarianBookOfEnlightenment_C.BPOnStart
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_LibrarianBookOfEnlightenment_C::BPOnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LibrarianBookOfEnlightenment_C", "BPOnStart");

	UObject::ProcessEvent(Func, nullptr);
}

}

