#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MinorRunestoneOfWandererComponent

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MinorRunestoneOfWandererComponent.BP_MinorRunestoneOfWandererComponent_C
// 0x0000 (0x0148 - 0x0148)
class UBP_MinorRunestoneOfWandererComponent_C final : public UComponentArray
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MinorRunestoneOfWandererComponent_C">();
	}
	static class UBP_MinorRunestoneOfWandererComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MinorRunestoneOfWandererComponent_C>();
	}
};
static_assert(alignof(UBP_MinorRunestoneOfWandererComponent_C) == 0x000008, "Wrong alignment on UBP_MinorRunestoneOfWandererComponent_C");
static_assert(sizeof(UBP_MinorRunestoneOfWandererComponent_C) == 0x000148, "Wrong size on UBP_MinorRunestoneOfWandererComponent_C");

}

