#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MotesOfChaos_Projectile_VE

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_MotesOfChaos_Projectile_VE.BP_MotesOfChaos_Projectile_VE_C.ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE
// 0x0004 (0x0004 - 0x0000)
struct BP_MotesOfChaos_Projectile_VE_C_ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MotesOfChaos_Projectile_VE_C_ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE) == 0x000004, "Wrong alignment on BP_MotesOfChaos_Projectile_VE_C_ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE");
static_assert(sizeof(BP_MotesOfChaos_Projectile_VE_C_ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE) == 0x000004, "Wrong size on BP_MotesOfChaos_Projectile_VE_C_ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE");
static_assert(offsetof(BP_MotesOfChaos_Projectile_VE_C_ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE, EntryPoint) == 0x000000, "Member 'BP_MotesOfChaos_Projectile_VE_C_ExecuteUbergraph_BP_MotesOfChaos_Projectile_VE::EntryPoint' has a wrong offset!");

}

