#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPCLittleGirlTutorial_Anim

#include "Basic.hpp"

#include "BP_NPCLittleGirlTutorial_Anim_classes.hpp"
#include "BP_NPCLittleGirlTutorial_Anim_parameters.hpp"


namespace SDK
{

// Function BP_NPCLittleGirlTutorial_Anim.BP_NPCLittleGirlTutorial_Anim_C.ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_NPCLittleGirlTutorial_Anim_C::ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCLittleGirlTutorial_Anim_C", "ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim");

	Params::BP_NPCLittleGirlTutorial_Anim_C_ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPCLittleGirlTutorial_Anim.BP_NPCLittleGirlTutorial_Anim_C.AnimNotify_OnLittleGirlStartIdle
// (BlueprintCallable, BlueprintEvent)

void UBP_NPCLittleGirlTutorial_Anim_C::AnimNotify_OnLittleGirlStartIdle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCLittleGirlTutorial_Anim_C", "AnimNotify_OnLittleGirlStartIdle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPCLittleGirlTutorial_Anim.BP_NPCLittleGirlTutorial_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim_AnimGraphNode_TransitionResult_6C1A3D164F3C85084B127A962150FAA1
// (BlueprintEvent)

void UBP_NPCLittleGirlTutorial_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim_AnimGraphNode_TransitionResult_6C1A3D164F3C85084B127A962150FAA1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCLittleGirlTutorial_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim_AnimGraphNode_TransitionResult_6C1A3D164F3C85084B127A962150FAA1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPCLittleGirlTutorial_Anim.BP_NPCLittleGirlTutorial_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim_AnimGraphNode_TransitionResult_9E871E824178A35C5020B09C77E5FDF7
// (BlueprintEvent)

void UBP_NPCLittleGirlTutorial_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim_AnimGraphNode_TransitionResult_9E871E824178A35C5020B09C77E5FDF7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCLittleGirlTutorial_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_NPCLittleGirlTutorial_Anim_AnimGraphNode_TransitionResult_9E871E824178A35C5020B09C77E5FDF7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPCLittleGirlTutorial_Anim.BP_NPCLittleGirlTutorial_Anim_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UBP_NPCLittleGirlTutorial_Anim_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCLittleGirlTutorial_Anim_C", "AnimGraph");

	Params::BP_NPCLittleGirlTutorial_Anim_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

