#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NewAreaTrigger

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NewAreaTrigger.BP_NewAreaTrigger_C
// 0x0010 (0x0800 - 0x07F0)
class ABP_NewAreaTrigger_C final : public ANewArea
{
public:
	class UTriggerBoxComponent*                   TriggerBox;                                        // 0x07F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x07F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NewAreaTrigger_C">();
	}
	static class ABP_NewAreaTrigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NewAreaTrigger_C>();
	}
};
static_assert(alignof(ABP_NewAreaTrigger_C) == 0x000008, "Wrong alignment on ABP_NewAreaTrigger_C");
static_assert(sizeof(ABP_NewAreaTrigger_C) == 0x000800, "Wrong size on ABP_NewAreaTrigger_C");
static_assert(offsetof(ABP_NewAreaTrigger_C, TriggerBox) == 0x0007F0, "Member 'ABP_NewAreaTrigger_C::TriggerBox' has a wrong offset!");
static_assert(offsetof(ABP_NewAreaTrigger_C, DefaultSceneRoot) == 0x0007F8, "Member 'ABP_NewAreaTrigger_C::DefaultSceneRoot' has a wrong offset!");

}

