#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Options_Controls_SelectHotkey

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_Options_Controls_SelectHotkey.BP_Options_Controls_SelectHotkey_C
// 0x0010 (0x04C8 - 0x04B8)
class UBP_Options_Controls_SelectHotkey_C final : public UOptionsSelectHotkeyUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Darkening;                                         // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Options_Controls_SelectHotkey(int32 EntryPoint);
	void OnHotkeyChangedEvent();
	void OnHotkeyCancelEvent();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Options_Controls_SelectHotkey_C">();
	}
	static class UBP_Options_Controls_SelectHotkey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Options_Controls_SelectHotkey_C>();
	}
};
static_assert(alignof(UBP_Options_Controls_SelectHotkey_C) == 0x000008, "Wrong alignment on UBP_Options_Controls_SelectHotkey_C");
static_assert(sizeof(UBP_Options_Controls_SelectHotkey_C) == 0x0004C8, "Wrong size on UBP_Options_Controls_SelectHotkey_C");
static_assert(offsetof(UBP_Options_Controls_SelectHotkey_C, UberGraphFrame) == 0x0004B8, "Member 'UBP_Options_Controls_SelectHotkey_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_Options_Controls_SelectHotkey_C, Darkening) == 0x0004C0, "Member 'UBP_Options_Controls_SelectHotkey_C::Darkening' has a wrong offset!");

}

