#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OrbofDoom_Anim_AimLoop_VisualEntity

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_OrbofDoom_Anim_AimLoop_VisualEntity.BP_OrbofDoom_Anim_AimLoop_VisualEntity_C.ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity
// 0x0004 (0x0004 - 0x0000)
struct BP_OrbofDoom_Anim_AimLoop_VisualEntity_C_ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_OrbofDoom_Anim_AimLoop_VisualEntity_C_ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity) == 0x000004, "Wrong alignment on BP_OrbofDoom_Anim_AimLoop_VisualEntity_C_ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity");
static_assert(sizeof(BP_OrbofDoom_Anim_AimLoop_VisualEntity_C_ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity) == 0x000004, "Wrong size on BP_OrbofDoom_Anim_AimLoop_VisualEntity_C_ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity");
static_assert(offsetof(BP_OrbofDoom_Anim_AimLoop_VisualEntity_C_ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity, EntryPoint) == 0x000000, "Member 'BP_OrbofDoom_Anim_AimLoop_VisualEntity_C_ExecuteUbergraph_BP_OrbofDoom_Anim_AimLoop_VisualEntity::EntryPoint' has a wrong offset!");

}

