#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OpenAbilityBase

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OpenAbilityBase.BP_OpenAbilityBase_C
// 0x0000 (0x0658 - 0x0658)
class UBP_OpenAbilityBase_C : public UOpenAbilityBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_OpenAbilityBase_C">();
	}
	static class UBP_OpenAbilityBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_OpenAbilityBase_C>();
	}
};
static_assert(alignof(UBP_OpenAbilityBase_C) == 0x000008, "Wrong alignment on UBP_OpenAbilityBase_C");
static_assert(sizeof(UBP_OpenAbilityBase_C) == 0x000658, "Wrong size on UBP_OpenAbilityBase_C");

}

