#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PotionofSpiritEffect

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PotionofSpiritEffect.BP_PotionofSpiritEffect_C
// 0x0000 (0x0630 - 0x0630)
class UBP_PotionofSpiritEffect_C final : public UEmptyPassiveAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PotionofSpiritEffect_C">();
	}
	static class UBP_PotionofSpiritEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PotionofSpiritEffect_C>();
	}
};
static_assert(alignof(UBP_PotionofSpiritEffect_C) == 0x000008, "Wrong alignment on UBP_PotionofSpiritEffect_C");
static_assert(sizeof(UBP_PotionofSpiritEffect_C) == 0x000630, "Wrong size on UBP_PotionofSpiritEffect_C");

}

