#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupItem_Craftmat

#include "Basic.hpp"

#include "BP_PickupItem_Craftmat_classes.hpp"
#include "BP_PickupItem_Craftmat_parameters.hpp"


namespace SDK
{

// Function BP_PickupItem_Craftmat.BP_PickupItem_Craftmat_C.ExecuteUbergraph_BP_PickupItem_Craftmat
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupItem_Craftmat_C::ExecuteUbergraph_BP_PickupItem_Craftmat(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupItem_Craftmat_C", "ExecuteUbergraph_BP_PickupItem_Craftmat");

	Params::BP_PickupItem_Craftmat_C_ExecuteUbergraph_BP_PickupItem_Craftmat Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PickupItem_Craftmat.BP_PickupItem_Craftmat_C.OnKill
// (Event, Protected, BlueprintEvent)

void ABP_PickupItem_Craftmat_C::OnKill()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupItem_Craftmat_C", "OnKill");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PickupItem_Craftmat.BP_PickupItem_Craftmat_C.VisualEntityConstructionFinished
// (Event, Protected, BlueprintEvent)

void ABP_PickupItem_Craftmat_C::VisualEntityConstructionFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupItem_Craftmat_C", "VisualEntityConstructionFinished");

	UObject::ProcessEvent(Func, nullptr);
}

}

