#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PouchOfGoldVisualEntity

#include "Basic.hpp"

#include "BP_PouchOfGoldVisualEntity_classes.hpp"
#include "BP_PouchOfGoldVisualEntity_parameters.hpp"


namespace SDK
{

// Function BP_PouchOfGoldVisualEntity.BP_PouchOfGoldVisualEntity_C.ExecuteUbergraph_BP_PouchOfGoldVisualEntity
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PouchOfGoldVisualEntity_C::ExecuteUbergraph_BP_PouchOfGoldVisualEntity(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PouchOfGoldVisualEntity_C", "ExecuteUbergraph_BP_PouchOfGoldVisualEntity");

	Params::BP_PouchOfGoldVisualEntity_C_ExecuteUbergraph_BP_PouchOfGoldVisualEntity Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PouchOfGoldVisualEntity.BP_PouchOfGoldVisualEntity_C.VisualEntityConstructionFinished
// (Event, Protected, BlueprintEvent)

void ABP_PouchOfGoldVisualEntity_C::VisualEntityConstructionFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PouchOfGoldVisualEntity_C", "VisualEntityConstructionFinished");

	UObject::ProcessEvent(Func, nullptr);
}

}

