#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PeriodicBTrapProjectile

#include "Basic.hpp"

#include "BP_PeriodicBTrapProjectile_classes.hpp"
#include "BP_PeriodicBTrapProjectile_parameters.hpp"


namespace SDK
{

// Function BP_PeriodicBTrapProjectile.BP_PeriodicBTrapProjectile_C.ExecuteUbergraph_BP_PeriodicBTrapProjectile
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PeriodicBTrapProjectile_C::ExecuteUbergraph_BP_PeriodicBTrapProjectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PeriodicBTrapProjectile_C", "ExecuteUbergraph_BP_PeriodicBTrapProjectile");

	Params::BP_PeriodicBTrapProjectile_C_ExecuteUbergraph_BP_PeriodicBTrapProjectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PeriodicBTrapProjectile.BP_PeriodicBTrapProjectile_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PeriodicBTrapProjectile_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PeriodicBTrapProjectile_C", "ReceiveEndPlay");

	Params::BP_PeriodicBTrapProjectile_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PeriodicBTrapProjectile.BP_PeriodicBTrapProjectile_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PeriodicBTrapProjectile_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PeriodicBTrapProjectile_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

