#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QuestWindow

#include "Basic.hpp"

#include "BP_QuestWindow_classes.hpp"
#include "BP_QuestWindow_parameters.hpp"


namespace SDK
{

// Function BP_QuestWindow.BP_QuestWindow_C.ExecuteUbergraph_BP_QuestWindow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_QuestWindow_C::ExecuteUbergraph_BP_QuestWindow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "ExecuteUbergraph_BP_QuestWindow");

	Params::BP_QuestWindow_C_ExecuteUbergraph_BP_QuestWindow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnSetInputDisplay
// (Event, Public, BlueprintEvent)
// Parameters:
// EInputDisplay                           InInputDisplay                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInputDisplay                           InControlDisplay                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_QuestWindow_C::OnSetInputDisplay(EInputDisplay InInputDisplay, EInputDisplay InControlDisplay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnSetInputDisplay");

	Params::BP_QuestWindow_C_OnSetInputDisplay Parms{};

	Parms.InInputDisplay = InInputDisplay;
	Parms.InControlDisplay = InControlDisplay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_BtnClose_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_BtnClose_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_BtnClose_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnIngameMenuEvent
// (Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::OnIngameMenuEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnIngameMenuEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_Tab_Map_1_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_Tab_Map_1_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_Tab_Map_1_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_Tab_WitchLantern_1_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_Tab_WitchLantern_1_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_Tab_WitchLantern_1_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_Tab_Skills_1_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_Tab_Skills_1_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_Tab_Skills_1_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_Tab_Attributes_1_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_Tab_Attributes_1_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_Tab_Attributes_1_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_Tab_Inventory_1_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_Tab_Inventory_1_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_Tab_Inventory_1_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_Tab_Character_1_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_Tab_Character_1_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_Tab_Character_1_K2Node_ComponentBoundEvent_9_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnGamepadLeftStickDownEvent
// (Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::OnGamepadLeftStickDownEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnGamepadLeftStickDownEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnGamepadLeftStickUpEvent
// (Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::OnGamepadLeftStickUpEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnGamepadLeftStickUpEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BP_QuestWindow_BtnHotkeyA_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BP_QuestWindow_BtnHotkeyA_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BP_QuestWindow_BtnHotkeyA_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnRebuildQuestList
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   InVisibleActiveQuestNum                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InVisibleBountyQuestNum                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InVisibleCompletedQuestNum                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_QuestWindow_C::OnRebuildQuestList(int32 InVisibleActiveQuestNum, int32 InVisibleBountyQuestNum, int32 InVisibleCompletedQuestNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnRebuildQuestList");

	Params::BP_QuestWindow_C_OnRebuildQuestList Parms{};

	Parms.InVisibleActiveQuestNum = InVisibleActiveQuestNum;
	Parms.InVisibleBountyQuestNum = InVisibleBountyQuestNum;
	Parms.InVisibleCompletedQuestNum = InVisibleCompletedQuestNum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnGamepadRBEvent
// (Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::OnGamepadRBEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnGamepadRBEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnGamepadLBEvent
// (Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::OnGamepadLBEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnGamepadLBEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BtnNextTab_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BtnNextTab_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BtnNextTab_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BtnPreviousTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BtnPreviousTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BtnPreviousTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BndEvt__BtnHotkeyB_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_QuestWindow_C::BndEvt__BtnHotkeyB_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BndEvt__BtnHotkeyB_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnSetSelectedQuest
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UManQuest*                        ManQuest                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             StoryText                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_QuestWindow_C::OnSetSelectedQuest(class UManQuest* ManQuest, const class FText& StoryText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnSetSelectedQuest");

	Params::BP_QuestWindow_C_OnSetSelectedQuest Parms{};

	Parms.ManQuest = ManQuest;
	Parms.StoryText = std::move(StoryText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnHide
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AnimDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_QuestWindow_C::OnHide(float AnimDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnHide");

	Params::BP_QuestWindow_C_OnHide Parms{};

	Parms.AnimDuration = AnimDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnShow
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AnimDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_QuestWindow_C::OnShow(float AnimDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnShow");

	Params::BP_QuestWindow_C_OnShow Parms{};

	Parms.AnimDuration = AnimDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnGamepadBEvent
// (Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::OnGamepadBEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnGamepadBEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.OnGamepadAEvent
// (Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::OnGamepadAEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "OnGamepadAEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_QuestWindow_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "Tick");

	Params::BP_QuestWindow_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_QuestWindow_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BP_SetSelectedQuest
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UManQuest*                        ManQuest                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             StoryText                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_QuestWindow_C::BP_SetSelectedQuest(class UManQuest* ManQuest, const class FText& StoryText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BP_SetSelectedQuest");

	Params::BP_QuestWindow_C_BP_SetSelectedQuest Parms{};

	Parms.ManQuest = ManQuest;
	Parms.StoryText = std::move(StoryText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BtnHotkeyBClicked
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    OpenPauseMenu                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_QuestWindow_C::BtnHotkeyBClicked(bool OpenPauseMenu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BtnHotkeyBClicked");

	Params::BP_QuestWindow_C_BtnHotkeyBClicked Parms{};

	Parms.OpenPauseMenu = OpenPauseMenu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.BtnHotkeyAClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_QuestWindow_C::BtnHotkeyAClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "BtnHotkeyAClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuestWindow.BP_QuestWindow_C.SetType
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIsMainQuest                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_QuestWindow_C::SetType(bool InIsMainQuest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "SetType");

	Params::BP_QuestWindow_C_SetType Parms{};

	Parms.InIsMainQuest = InIsMainQuest;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuestWindow.BP_QuestWindow_C.SetBtnCloseVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_QuestWindow_C::SetBtnCloseVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuestWindow_C", "SetBtnCloseVisibility");

	UObject::ProcessEvent(Func, nullptr);
}

}

