#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rosalie

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Rosalie.BP_Rosalie_C.ExecuteUbergraph_BP_Rosalie
// 0x0004 (0x0004 - 0x0000)
struct BP_Rosalie_C_ExecuteUbergraph_BP_Rosalie final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Rosalie_C_ExecuteUbergraph_BP_Rosalie) == 0x000004, "Wrong alignment on BP_Rosalie_C_ExecuteUbergraph_BP_Rosalie");
static_assert(sizeof(BP_Rosalie_C_ExecuteUbergraph_BP_Rosalie) == 0x000004, "Wrong size on BP_Rosalie_C_ExecuteUbergraph_BP_Rosalie");
static_assert(offsetof(BP_Rosalie_C_ExecuteUbergraph_BP_Rosalie, EntryPoint) == 0x000000, "Member 'BP_Rosalie_C_ExecuteUbergraph_BP_Rosalie::EntryPoint' has a wrong offset!");

}

