#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Smash_TerrorWolf_VisualEntity

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Smash_TerrorWolf_VisualEntity.BP_Smash_TerrorWolf_VisualEntity_C.ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity
// 0x0008 (0x0008 - 0x0000)
struct BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Lerp_ReturnValue;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity) == 0x000004, "Wrong alignment on BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity");
static_assert(sizeof(BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity) == 0x000008, "Wrong size on BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity");
static_assert(offsetof(BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity, EntryPoint) == 0x000000, "Member 'BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity, CallFunc_Lerp_ReturnValue) == 0x000004, "Member 'BP_Smash_TerrorWolf_VisualEntity_C_ExecuteUbergraph_BP_Smash_TerrorWolf_VisualEntity::CallFunc_Lerp_ReturnValue' has a wrong offset!");

}

