#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SummonedBook

#include "Basic.hpp"

#include "BP_SummonedBook_classes.hpp"
#include "BP_SummonedBook_parameters.hpp"


namespace SDK
{

// Function BP_SummonedBook.BP_SummonedBook_C.ExecuteUbergraph_BP_SummonedBook
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SummonedBook_C::ExecuteUbergraph_BP_SummonedBook(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "ExecuteUbergraph_BP_SummonedBook");

	Params::BP_SummonedBook_C_ExecuteUbergraph_BP_SummonedBook Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SummonedBook.BP_SummonedBook_C.BPPostBeginPlay
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_SummonedBook_C::BPPostBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "BPPostBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SummonedBook.BP_SummonedBook_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SummonedBook_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SummonedBook.BP_SummonedBook_C.DisappearVFX
// (BlueprintCallable, BlueprintEvent)

void ABP_SummonedBook_C::DisappearVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "DisappearVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SummonedBook.BP_SummonedBook_C.AppearVFX
// (BlueprintCallable, BlueprintEvent)

void ABP_SummonedBook_C::AppearVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "AppearVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SummonedBook.BP_SummonedBook_C.DissolveTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_SummonedBook_C::DissolveTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "DissolveTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SummonedBook.BP_SummonedBook_C.DissolveTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_SummonedBook_C::DissolveTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "DissolveTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SummonedBook.BP_SummonedBook_C.GetColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     Color                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SummonedBook_C::GetColor(struct FLinearColor* Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SummonedBook_C", "GetColor");

	Params::BP_SummonedBook_C_GetColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Color != nullptr)
		*Color = std::move(Parms.Color);
}

}

