#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SimpleSplineMesh

#include "Basic.hpp"

#include "BP_SimpleSplineMesh_classes.hpp"
#include "BP_SimpleSplineMesh_parameters.hpp"


namespace SDK
{

// Function BP_SimpleSplineMesh.BP_SimpleSplineMesh_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SimpleSplineMesh_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SimpleSplineMesh_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

