#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SideDoor_ActorBase

#include "Basic.hpp"

#include "BP_SideDoor_ActorBase_classes.hpp"
#include "BP_SideDoor_ActorBase_parameters.hpp"


namespace SDK
{

// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SideDoor_ActorBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ABP_SideDoor_ActorBase_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ABP_SideDoor_ActorBase_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.OnVfxEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             VfxEventType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SideDoor_ActorBase_C::OnVfxEvent(class FName VfxEventType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "OnVfxEvent");

	Params::BP_SideDoor_ActorBase_C_OnVfxEvent Parms{};

	Parms.VfxEventType = VfxEventType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.BPOnOpened
// (Event, Public, BlueprintEvent)

void ABP_SideDoor_ActorBase_C::BPOnOpened()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "BPOnOpened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.BPOnClosed
// (Event, Public, BlueprintEvent)

void ABP_SideDoor_ActorBase_C::BPOnClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "BPOnClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SideDoor_ActorBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SideDoor_ActorBase.BP_SideDoor_ActorBase_C.ExecuteUbergraph_BP_SideDoor_ActorBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SideDoor_ActorBase_C::ExecuteUbergraph_BP_SideDoor_ActorBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SideDoor_ActorBase_C", "ExecuteUbergraph_BP_SideDoor_ActorBase");

	Params::BP_SideDoor_ActorBase_C_ExecuteUbergraph_BP_SideDoor_ActorBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

