#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SaveGameScreen

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_SaveGameScreen.BP_SaveGameScreen_C
// 0x0008 (0x04B8 - 0x04B0)
class UBP_SaveGameScreen_C final : public USaveGameUserWidget
{
public:
	class UImage*                                 LoadingAnim;                                       // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SaveGameScreen_C">();
	}
	static class UBP_SaveGameScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SaveGameScreen_C>();
	}
};
static_assert(alignof(UBP_SaveGameScreen_C) == 0x000008, "Wrong alignment on UBP_SaveGameScreen_C");
static_assert(sizeof(UBP_SaveGameScreen_C) == 0x0004B8, "Wrong size on UBP_SaveGameScreen_C");
static_assert(offsetof(UBP_SaveGameScreen_C, LoadingAnim) == 0x0004B0, "Member 'UBP_SaveGameScreen_C::LoadingAnim' has a wrong offset!");

}

