#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StrigaDodge

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StrigaDodge.BP_StrigaDodge_C
// 0x0000 (0x0608 - 0x0608)
class UBP_StrigaDodge_C final : public UEmptyAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_StrigaDodge_C">();
	}
	static class UBP_StrigaDodge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_StrigaDodge_C>();
	}
};
static_assert(alignof(UBP_StrigaDodge_C) == 0x000008, "Wrong alignment on UBP_StrigaDodge_C");
static_assert(sizeof(UBP_StrigaDodge_C) == 0x000608, "Wrong size on UBP_StrigaDodge_C");

}

