#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SunderOnWeapon_VisualEntity

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SunderOnWeapon_VisualEntity.BP_SunderOnWeapon_VisualEntity_C
// 0x0010 (0x0360 - 0x0350)
class ABP_SunderOnWeapon_VisualEntity_C final : public AVisualEntity
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_WeaponActor_THM_C*                  Weapon;                                            // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_SunderOnWeapon_VisualEntity(int32 EntryPoint);
	void OnKill();
	void VisualEntityConstructionFinished();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SunderOnWeapon_VisualEntity_C">();
	}
	static class ABP_SunderOnWeapon_VisualEntity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SunderOnWeapon_VisualEntity_C>();
	}
};
static_assert(alignof(ABP_SunderOnWeapon_VisualEntity_C) == 0x000008, "Wrong alignment on ABP_SunderOnWeapon_VisualEntity_C");
static_assert(sizeof(ABP_SunderOnWeapon_VisualEntity_C) == 0x000360, "Wrong size on ABP_SunderOnWeapon_VisualEntity_C");
static_assert(offsetof(ABP_SunderOnWeapon_VisualEntity_C, UberGraphFrame) == 0x000350, "Member 'ABP_SunderOnWeapon_VisualEntity_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_SunderOnWeapon_VisualEntity_C, Weapon) == 0x000358, "Member 'ABP_SunderOnWeapon_VisualEntity_C::Weapon' has a wrong offset!");

}

