#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StrigaLacerateAbility

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StrigaLacerateAbility.BP_StrigaLacerateAbility_C
// 0x0000 (0x0680 - 0x0680)
class UBP_StrigaLacerateAbility_C final : public UStrigaLacerateAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_StrigaLacerateAbility_C">();
	}
	static class UBP_StrigaLacerateAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_StrigaLacerateAbility_C>();
	}
};
static_assert(alignof(UBP_StrigaLacerateAbility_C) == 0x000008, "Wrong alignment on UBP_StrigaLacerateAbility_C");
static_assert(sizeof(UBP_StrigaLacerateAbility_C) == 0x000680, "Wrong size on UBP_StrigaLacerateAbility_C");

}

