#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpiritWolf_Anim

#include "Basic.hpp"

#include "BP_SpiritWolf_Anim_classes.hpp"
#include "BP_SpiritWolf_Anim_parameters.hpp"


namespace SDK
{

// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.ExecuteUbergraph_BP_SpiritWolf_Anim
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SpiritWolf_Anim_C::ExecuteUbergraph_BP_SpiritWolf_Anim(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "ExecuteUbergraph_BP_SpiritWolf_Anim");

	Params::BP_SpiritWolf_Anim_C_ExecuteUbergraph_BP_SpiritWolf_Anim Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.BlueprintBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_SpiritWolf_Anim_C::BlueprintBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "BlueprintBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.OnFacingChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bForced                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_SpiritWolf_Anim_C::OnFacingChanged(bool bForced)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "OnFacingChanged");

	Params::BP_SpiritWolf_Anim_C_OnFacingChanged Parms{};

	Parms.bForced = bForced;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_BlendListByInt_93279E724A874EE7D0AEE987670287B7
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_BlendListByInt_93279E724A874EE7D0AEE987670287B7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_BlendListByInt_93279E724A874EE7D0AEE987670287B7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_F7BC56D441040409AF9713820FBBC970
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_F7BC56D441040409AF9713820FBBC970()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_F7BC56D441040409AF9713820FBBC970");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SpiritWolf_Anim_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "BlueprintUpdateAnimation");

	Params::BP_SpiritWolf_Anim_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_9C0CAAB747A81A6F11287BA1C05665B4
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_9C0CAAB747A81A6F11287BA1C05665B4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_9C0CAAB747A81A6F11287BA1C05665B4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_DDE8D15B4FB90B9A0744A19182FDC086
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_DDE8D15B4FB90B9A0744A19182FDC086()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_DDE8D15B4FB90B9A0744A19182FDC086");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_936C28A14364E1CC13DAC6AFA64AF64F
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_936C28A14364E1CC13DAC6AFA64AF64F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_936C28A14364E1CC13DAC6AFA64AF64F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_4C0264434D6AA1F5D2DDA58DC571E0C4
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_4C0264434D6AA1F5D2DDA58DC571E0C4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_4C0264434D6AA1F5D2DDA58DC571E0C4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_56AFF49346C8994C1EA118AFBED17DCF
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_56AFF49346C8994C1EA118AFBED17DCF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_56AFF49346C8994C1EA118AFBED17DCF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_78A58CEB4FF06F249AA5249D5B2A5B7B
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_78A58CEB4FF06F249AA5249D5B2A5B7B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_ModifyBone_78A58CEB4FF06F249AA5249D5B2A5B7B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_TransitionResult_C2A19DF549DC6BAB1B31E688BC5233B9
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_TransitionResult_C2A19DF549DC6BAB1B31E688BC5233B9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_TransitionResult_C2A19DF549DC6BAB1B31E688BC5233B9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_TransitionResult_65C35EC546321EC600DE949C088EC7C5
// (BlueprintEvent)

void UBP_SpiritWolf_Anim_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_TransitionResult_65C35EC546321EC600DE949C088EC7C5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_SpiritWolf_Anim_AnimGraphNode_TransitionResult_65C35EC546321EC600DE949C088EC7C5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SpiritWolf_Anim.BP_SpiritWolf_Anim_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UBP_SpiritWolf_Anim_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SpiritWolf_Anim_C", "AnimGraph");

	Params::BP_SpiritWolf_Anim_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

