#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TerrorWolfAI

#include "Basic.hpp"

#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TerrorWolfAI.BP_TerrorWolfAI_C
// 0x0000 (0x10F8 - 0x10F8)
class UBP_TerrorWolfAI_C final : public UTerrorWolfAI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TerrorWolfAI_C">();
	}
	static class UBP_TerrorWolfAI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TerrorWolfAI_C>();
	}
};
static_assert(alignof(UBP_TerrorWolfAI_C) == 0x000008, "Wrong alignment on UBP_TerrorWolfAI_C");
static_assert(sizeof(UBP_TerrorWolfAI_C) == 0x0010F8, "Wrong size on UBP_TerrorWolfAI_C");

}

