#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TrainingSpearman2

#include "Basic.hpp"

#include "BP_TrainingSpearman2_classes.hpp"
#include "BP_TrainingSpearman2_parameters.hpp"


namespace SDK
{

// Function BP_TrainingSpearman2.BP_TrainingSpearman2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_TrainingSpearman2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TrainingSpearman2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TrainingSpearman2.BP_TrainingSpearman2_C.ExecuteUbergraph_BP_TrainingSpearman2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TrainingSpearman2_C::ExecuteUbergraph_BP_TrainingSpearman2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TrainingSpearman2_C", "ExecuteUbergraph_BP_TrainingSpearman2");

	Params::BP_TrainingSpearman2_C_ExecuteUbergraph_BP_TrainingSpearman2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

