#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TailorDiagramBackPickupSpeechTable

#include "Basic.hpp"

#include "BP_SpeechTableBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TailorDiagramBackPickupSpeechTable.BP_TailorDiagramBackPickupSpeechTable_C
// 0x0000 (0x0640 - 0x0640)
class UBP_TailorDiagramBackPickupSpeechTable_C final : public UBP_SpeechTableBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TailorDiagramBackPickupSpeechTable_C">();
	}
	static class UBP_TailorDiagramBackPickupSpeechTable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TailorDiagramBackPickupSpeechTable_C>();
	}
};
static_assert(alignof(UBP_TailorDiagramBackPickupSpeechTable_C) == 0x000008, "Wrong alignment on UBP_TailorDiagramBackPickupSpeechTable_C");
static_assert(sizeof(UBP_TailorDiagramBackPickupSpeechTable_C) == 0x000640, "Wrong size on UBP_TailorDiagramBackPickupSpeechTable_C");

}

