#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UnstableElements_PassiveSkill

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UnstableElements_PassiveSkill.BP_UnstableElements_PassiveSkill_C
// 0x0008 (0x0650 - 0x0648)
class UBP_UnstableElements_PassiveSkill_C final : public UUnstableElements
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0648(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_UnstableElements_PassiveSkill(int32 EntryPoint);
	void BPAbilityCustomEvent(class FName CustomName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UnstableElements_PassiveSkill_C">();
	}
	static class UBP_UnstableElements_PassiveSkill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UnstableElements_PassiveSkill_C>();
	}
};
static_assert(alignof(UBP_UnstableElements_PassiveSkill_C) == 0x000008, "Wrong alignment on UBP_UnstableElements_PassiveSkill_C");
static_assert(sizeof(UBP_UnstableElements_PassiveSkill_C) == 0x000650, "Wrong size on UBP_UnstableElements_PassiveSkill_C");
static_assert(offsetof(UBP_UnstableElements_PassiveSkill_C, UberGraphFrame) == 0x000648, "Member 'UBP_UnstableElements_PassiveSkill_C::UberGraphFrame' has a wrong offset!");

}

