#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UpsweptSlicer_ItemAbility

#include "Basic.hpp"

#include "BP_OneHandedWeapon_ItemAbility_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UpsweptSlicer_ItemAbility.BP_UpsweptSlicer_ItemAbility_C
// 0x0000 (0x07F0 - 0x07F0)
class UBP_UpsweptSlicer_ItemAbility_C final : public UBP_OneHandedWeapon_ItemAbility_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UpsweptSlicer_ItemAbility_C">();
	}
	static class UBP_UpsweptSlicer_ItemAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UpsweptSlicer_ItemAbility_C>();
	}
};
static_assert(alignof(UBP_UpsweptSlicer_ItemAbility_C) == 0x000008, "Wrong alignment on UBP_UpsweptSlicer_ItemAbility_C");
static_assert(sizeof(UBP_UpsweptSlicer_ItemAbility_C) == 0x0007F0, "Wrong size on UBP_UpsweptSlicer_ItemAbility_C");

}

