#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VfxComponentBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VfxComponentBase.BP_VfxComponentBase_C
// 0x0010 (0x0710 - 0x0700)
#pragma pack(push, 0x1)
class alignas(0x10) UBP_VfxComponentBase_C : public UVfxComponentBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0700(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_VfxComponentBase(int32 EntryPoint);
	void BPTick(float DeltaTime);
	void BPForceKill();
	void BPStart();
	void RenderTargetProperties(class UTextureRenderTarget2D* RenderTargetInput, ETexturePowerOfTwoSetting Pow2, ETextureAddress TileX, ETextureAddress TileY, ETextureFilter Filter);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VfxComponentBase_C">();
	}
	static class UBP_VfxComponentBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_VfxComponentBase_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(UBP_VfxComponentBase_C) == 0x000010, "Wrong alignment on UBP_VfxComponentBase_C");
static_assert(sizeof(UBP_VfxComponentBase_C) == 0x000710, "Wrong size on UBP_VfxComponentBase_C");
static_assert(offsetof(UBP_VfxComponentBase_C, UberGraphFrame) == 0x000700, "Member 'UBP_VfxComponentBase_C::UberGraphFrame' has a wrong offset!");

}

