#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vendor_Craft

#include "Basic.hpp"

#include "BP_Vendor_Craft_classes.hpp"
#include "BP_Vendor_Craft_parameters.hpp"


namespace SDK
{

// Function BP_Vendor_Craft.BP_Vendor_Craft_C.ExecuteUbergraph_BP_Vendor_Craft
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::ExecuteUbergraph_BP_Vendor_Craft(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "ExecuteUbergraph_BP_Vendor_Craft");

	Params::BP_Vendor_Craft_C_ExecuteUbergraph_BP_Vendor_Craft Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnSetInputDisplay
// (Event, Public, BlueprintEvent)
// Parameters:
// EInputDisplay                           InInputDisplay                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInputDisplay                           InControlDisplay                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::OnSetInputDisplay(EInputDisplay InInputDisplay, EInputDisplay InControlDisplay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnSetInputDisplay");

	Params::BP_Vendor_Craft_C_OnSetInputDisplay Parms{};

	Parms.InInputDisplay = InInputDisplay;
	Parms.InControlDisplay = InControlDisplay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Alchemist_BtnClose_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Alchemist_BtnClose_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Alchemist_BtnClose_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnCultureChanged
// (Event, Protected, BlueprintEvent)

void UBP_Vendor_Craft_C::OnCultureChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnCultureChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnErrorHiglight
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UInteractButtonUserWidget*        InteractButtonUserWidget                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::OnErrorHiglight(class UInteractButtonUserWidget* InteractButtonUserWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnErrorHiglight");

	Params::BP_Vendor_Craft_C_OnErrorHiglight Parms{};

	Parms.InteractButtonUserWidget = InteractButtonUserWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadRightStickDownEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadRightStickDownEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadRightStickDownEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadRightStickUpEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadRightStickUpEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadRightStickUpEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Conversation_Tab_Transmog_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Conversation_Tab_Transmog_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Conversation_Tab_Transmog_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Conversation_Tab_MapFragments_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Conversation_Tab_MapFragments_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Conversation_Tab_MapFragments_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Enchant_Tab_Upgrade_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Enchant_Tab_Upgrade_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Enchant_Tab_Upgrade_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnUpdateSelectedItemDetailsPanel
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             ItemRequirementText                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UItemAbility*                     InItem                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemAbility*                     InComparedItem                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bEquipped                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bAnimate                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::OnUpdateSelectedItemDetailsPanel(const class FText& ItemRequirementText, class UItemAbility* InItem, class UItemAbility* InComparedItem, bool bEquipped, bool bAnimate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnUpdateSelectedItemDetailsPanel");

	Params::BP_Vendor_Craft_C_OnUpdateSelectedItemDetailsPanel Parms{};

	Parms.ItemRequirementText = std::move(ItemRequirementText);
	Parms.InItem = InItem;
	Parms.InComparedItem = InComparedItem;
	Parms.bEquipped = bEquipped;
	Parms.bAnimate = bAnimate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadLeftStickBtnEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadLeftStickBtnEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadLeftStickBtnEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnHoldFinished
// (Event, Public, BlueprintEvent)
// Parameters:
// class UInteractButtonUserWidget*        InteractButtonUserWidget                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::OnHoldFinished(class UInteractButtonUserWidget* InteractButtonUserWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnHoldFinished");

	Params::BP_Vendor_Craft_C_OnHoldFinished Parms{};

	Parms.InteractButtonUserWidget = InteractButtonUserWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnHoldCanceled
// (Event, Public, BlueprintEvent)
// Parameters:
// class UInteractButtonUserWidget*        InteractButtonUserWidget                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bMinTimeCancel                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::OnHoldCanceled(class UInteractButtonUserWidget* InteractButtonUserWidget, bool bMinTimeCancel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnHoldCanceled");

	Params::BP_Vendor_Craft_C_OnHoldCanceled Parms{};

	Parms.InteractButtonUserWidget = InteractButtonUserWidget;
	Parms.bMinTimeCancel = bMinTimeCancel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnHoldStarted
// (Event, Public, BlueprintEvent)
// Parameters:
// class UInteractButtonUserWidget*        InteractButtonUserWidget                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::OnHoldStarted(class UInteractButtonUserWidget* InteractButtonUserWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnHoldStarted");

	Params::BP_Vendor_Craft_C_OnHoldStarted Parms{};

	Parms.InteractButtonUserWidget = InteractButtonUserWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Sell_Filter_All_K2Node_ComponentBoundEvent_26_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Sell_Filter_All_K2Node_ComponentBoundEvent_26_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Sell_Filter_All_K2Node_ComponentBoundEvent_26_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_Vendor_Sell_Filter_All_K2Node_ComponentBoundEvent_26_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Diagrams_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Diagrams_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Diagrams_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Diagrams_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_QuickUse_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_QuickUse_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_QuickUse_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_QuickUse_K2Node_ComponentBoundEvent_25_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_QuestItems_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_QuestItems_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_QuestItems_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_QuestItems_K2Node_ComponentBoundEvent_24_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Materials_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Materials_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Materials_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Materials_K2Node_ComponentBoundEvent_23_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Ring_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Ring_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Ring_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Ring_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Back_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Back_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Back_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Back_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Legs_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Legs_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Legs_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Legs_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Hands_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Hands_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Hands_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Hands_K2Node_ComponentBoundEvent_18_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Head_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Head_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Head_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Head_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Chest_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Chest_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Chest_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Chest_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_Offhand_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_Offhand_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_Offhand_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_Offhand_K2Node_ComponentBoundEvent_12_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_InventoryWindow_Filter_MainHand_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UVendorFilterSlotUserWidget*      WidgetReference                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::BndEvt__BP_InventoryWindow_Filter_MainHand_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature(class UVendorFilterSlotUserWidget* WidgetReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_InventoryWindow_Filter_MainHand_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature");

	Params::BP_Vendor_Craft_C_BndEvt__BP_InventoryWindow_Filter_MainHand_K2Node_ComponentBoundEvent_7_OnClicked__DelegateSignature Parms{};

	Parms.WidgetReference = WidgetReference;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Buy_Btn_Decrease_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Buy_Btn_Decrease_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Buy_Btn_Decrease_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Buy_Btn_Increase_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Buy_Btn_Increase_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Buy_Btn_Increase_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnSetFilterSlot
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// EItemSlot                               ItemSlot                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             FilterName                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_Vendor_Craft_C::OnSetFilterSlot(EItemSlot ItemSlot, const class FText& FilterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnSetFilterSlot");

	Params::BP_Vendor_Craft_C_OnSetFilterSlot Parms{};

	Parms.ItemSlot = ItemSlot;
	Parms.FilterName = std::move(FilterName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnSortChanged
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             SortName                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_Vendor_Craft_C::OnSortChanged(const class FText& SortName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnSortChanged");

	Params::BP_Vendor_Craft_C_OnSortChanged Parms{};

	Parms.SortName = std::move(SortName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnSetSelectedItemProperty
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class UTexture2D*                       InItemIcon                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             InItemName                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   InSelectedCount                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InMaxCount                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             InPriceText                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             InPriceGoldValue                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             InPriceEssenceValue                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             InRequirementText                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             InItemTypeText                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bHasEnoughGold                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bHasEnoughEssence                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::OnSetSelectedItemProperty(class UTexture2D* InItemIcon, const class FText& InItemName, int32 InSelectedCount, int32 InMaxCount, const class FText& InPriceText, const class FText& InPriceGoldValue, const class FText& InPriceEssenceValue, const class FText& InRequirementText, const class FText& InItemTypeText, bool bHasEnoughGold, bool bHasEnoughEssence)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnSetSelectedItemProperty");

	Params::BP_Vendor_Craft_C_OnSetSelectedItemProperty Parms{};

	Parms.InItemIcon = InItemIcon;
	Parms.InItemName = std::move(InItemName);
	Parms.InSelectedCount = InSelectedCount;
	Parms.InMaxCount = InMaxCount;
	Parms.InPriceText = std::move(InPriceText);
	Parms.InPriceGoldValue = std::move(InPriceGoldValue);
	Parms.InPriceEssenceValue = std::move(InPriceEssenceValue);
	Parms.InRequirementText = std::move(InRequirementText);
	Parms.InItemTypeText = std::move(InItemTypeText);
	Parms.bHasEnoughGold = bHasEnoughGold;
	Parms.bHasEnoughEssence = bHasEnoughEssence;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnSetVendorName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             VendorName_0                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_Vendor_Craft_C::OnSetVendorName(const class FText& VendorName_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnSetVendorName");

	Params::BP_Vendor_Craft_C_OnSetVendorName Parms{};

	Parms.VendorName_0 = std::move(VendorName_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Sell_BtnHotkeyDPadUpDown_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Sell_BtnHotkeyDPadUpDown_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Sell_BtnHotkeyDPadUpDown_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_BtnHotkeyRT_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_BtnHotkeyRT_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_BtnHotkeyRT_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_BtnHotkeyLT_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_BtnHotkeyLT_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_BtnHotkeyLT_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_BtnNextTab_1_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_BtnNextTab_1_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_BtnNextTab_1_K2Node_ComponentBoundEvent_22_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_Tab_Talk_1_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_Tab_Talk_1_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_Tab_Talk_1_K2Node_ComponentBoundEvent_21_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_Tab_Bestiary_1_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_Tab_Bestiary_1_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_Tab_Bestiary_1_K2Node_ComponentBoundEvent_20_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_Tab_Garden_1_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_Tab_Garden_1_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_Tab_Garden_1_K2Node_ComponentBoundEvent_19_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_Tab_Upgrade_1_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_Tab_Upgrade_1_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_Tab_Upgrade_1_K2Node_ComponentBoundEvent_17_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_Tab_Craft_1_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_Tab_Craft_1_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_Tab_Craft_1_K2Node_ComponentBoundEvent_16_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_Tab_Sell_1_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_Tab_Sell_1_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_Tab_Sell_1_K2Node_ComponentBoundEvent_15_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_Tab_Buy_1_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_Tab_Buy_1_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_Tab_Buy_1_K2Node_ComponentBoundEvent_13_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BP_Vendor_Craft_BtnPreviousTab_1_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BP_Vendor_Craft_BtnPreviousTab_1_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BP_Vendor_Craft_BtnPreviousTab_1_K2Node_ComponentBoundEvent_10_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadLTEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadLTEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadLTEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadRTEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadRTEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadRTEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnCraftItem
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    InLevelUp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::OnCraftItem(bool InLevelUp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnCraftItem");

	Params::BP_Vendor_Craft_C_OnCraftItem Parms{};

	Parms.InLevelUp = InLevelUp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BtnHotkeyRS_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BtnHotkeyRS_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BtnHotkeyRS_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadRBEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadRBEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadRBEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadLBEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadLBEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadLBEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BndEvt__BtnClose_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UBP_Vendor_Craft_C::BndEvt__BtnClose_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BndEvt__BtnClose_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnGamepadBEvent
// (Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnGamepadBEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnGamepadBEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnHide
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AnimDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::OnHide(float AnimDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnHide");

	Params::BP_Vendor_Craft_C_OnHide Parms{};

	Parms.AnimDuration = AnimDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnShow
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   AnimDuration                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::OnShow(float AnimDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnShow");

	Params::BP_Vendor_Craft_C_OnShow Parms{};

	Parms.AnimDuration = AnimDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_Vendor_Craft_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "Tick");

	Params::BP_Vendor_Craft_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "PreConstruct");

	Params::BP_Vendor_Craft_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BtnHotkeyBClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::BtnHotkeyBClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BtnHotkeyBClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.ShowItemLore
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::ShowItemLore()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "ShowItemLore");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.HideItemLore
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::HideItemLore()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "HideItemLore");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BtnHotkeyLS_PressClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::BtnHotkeyLS_PressClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BtnHotkeyLS_PressClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetCurrency
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InPriceText                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             InPriceGoldValue                                       (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             InPriceEssenceValue                                    (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_Vendor_Craft_C::SetCurrency(const class FText& InPriceText, const class FText& InPriceGoldValue, const class FText& InPriceEssenceValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetCurrency");

	Params::BP_Vendor_Craft_C_SetCurrency Parms{};

	Parms.InPriceText = std::move(InPriceText);
	Parms.InPriceGoldValue = std::move(InPriceGoldValue);
	Parms.InPriceEssenceValue = std::move(InPriceEssenceValue);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetVendorParams
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlayAnim                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::SetVendorParams(bool PlayAnim)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetVendorParams");

	Params::BP_Vendor_Craft_C_SetVendorParams Parms{};

	Parms.PlayAnim = PlayAnim;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetXP
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InCurrentXP                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InCurrentLevelXP                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InNextLevelXP                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    PlayAnim                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::SetXP(float InCurrentXP, float InCurrentLevelXP, float InNextLevelXP, bool PlayAnim)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetXP");

	Params::BP_Vendor_Craft_C_SetXP Parms{};

	Parms.InCurrentXP = InCurrentXP;
	Parms.InCurrentLevelXP = InCurrentLevelXP;
	Parms.InNextLevelXP = InNextLevelXP;
	Parms.PlayAnim = PlayAnim;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetXPLevelUp
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::SetXPLevelUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetXPLevelUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetHeroResource
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::SetHeroResource()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetHeroResource");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.CraftFinished
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::CraftFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "CraftFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BtnHotkeyRSUpClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::BtnHotkeyRSUpClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BtnHotkeyRSUpClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BtnHotkeyRSDownClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::BtnHotkeyRSDownClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BtnHotkeyRSDownClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BtnHotkeyRTClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::BtnHotkeyRTClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BtnHotkeyRTClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BtnHotkeyLTClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::BtnHotkeyLTClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BtnHotkeyLTClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetSelectedItemProperty
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       InItemIcon                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             InItemName                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   InSelectedCount                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InMaxCount                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             InPriceText                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             InPriceGoldValue                                       (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             InPriceEssenceValue                                    (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             InRequirementText                                      (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    HasEnoughGold                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HasEnoughEssence                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Vendor_Craft_C::SetSelectedItemProperty(class UTexture2D* InItemIcon, const class FText& InItemName, int32 InSelectedCount, int32 InMaxCount, const class FText& InPriceText, const class FText& InPriceGoldValue, const class FText& InPriceEssenceValue, const class FText& InRequirementText, bool HasEnoughGold, bool HasEnoughEssence)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetSelectedItemProperty");

	Params::BP_Vendor_Craft_C_SetSelectedItemProperty Parms{};

	Parms.InItemIcon = InItemIcon;
	Parms.InItemName = std::move(InItemName);
	Parms.InSelectedCount = InSelectedCount;
	Parms.InMaxCount = InMaxCount;
	Parms.InPriceText = std::move(InPriceText);
	Parms.InPriceGoldValue = std::move(InPriceGoldValue);
	Parms.InPriceEssenceValue = std::move(InPriceEssenceValue);
	Parms.InRequirementText = std::move(InRequirementText);
	Parms.HasEnoughGold = HasEnoughGold;
	Parms.HasEnoughEssence = HasEnoughEssence;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetRightPanelDisabled
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InDisabled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InHasEnoughGold                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    InHasEnoughEssence                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsUnavailableByResource                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   InSelectedCount                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InMaxCount                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Vendor_Craft_C::SetRightPanelDisabled(bool InDisabled, bool InHasEnoughGold, bool InHasEnoughEssence, bool IsUnavailableByResource, int32 InSelectedCount, int32 InMaxCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetRightPanelDisabled");

	Params::BP_Vendor_Craft_C_SetRightPanelDisabled Parms{};

	Parms.InDisabled = InDisabled;
	Parms.InHasEnoughGold = InHasEnoughGold;
	Parms.InHasEnoughEssence = InHasEnoughEssence;
	Parms.IsUnavailableByResource = IsUnavailableByResource;
	Parms.InSelectedCount = InSelectedCount;
	Parms.InMaxCount = InMaxCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.UpdateSelectedItemAnimSlot
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::UpdateSelectedItemAnimSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "UpdateSelectedItemAnimSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.BalanceErrorHighlight
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::BalanceErrorHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "BalanceErrorHighlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.SetBtnCloseVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::SetBtnCloseVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "SetBtnCloseVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Vendor_Craft.BP_Vendor_Craft_C.XPBar Value Anim Finished
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_Vendor_Craft_C::XPBar_Value_Anim_Finished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Vendor_Craft_C", "XPBar Value Anim Finished");

	UObject::ProcessEvent(Func, nullptr);
}

}

