#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WoolBandage_Item

#include "Basic.hpp"

#include "BP_WoolBandage_Item_classes.hpp"
#include "BP_WoolBandage_Item_parameters.hpp"


namespace SDK
{

// Function BP_WoolBandage_Item.BP_WoolBandage_Item_C.BPStartCondition
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_WoolBandage_Item_C::BPStartCondition(bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WoolBandage_Item_C", "BPStartCondition");

	Params::BP_WoolBandage_Item_C_BPStartCondition Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}

}

