#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BQ01_TerrorWolf_Quest

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BQ01_TerrorWolf_Quest.BQ01_TerrorWolf_Quest_C
// 0x0008 (0x0178 - 0x0170)
class UBQ01_TerrorWolf_Quest_C final : public UManQuest
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0170(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BQ01_TerrorWolf_Quest(int32 EntryPoint);
	void ConstructQuestObjectives();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BQ01_TerrorWolf_Quest_C">();
	}
	static class UBQ01_TerrorWolf_Quest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBQ01_TerrorWolf_Quest_C>();
	}
};
static_assert(alignof(UBQ01_TerrorWolf_Quest_C) == 0x000008, "Wrong alignment on UBQ01_TerrorWolf_Quest_C");
static_assert(sizeof(UBQ01_TerrorWolf_Quest_C) == 0x000178, "Wrong size on UBQ01_TerrorWolf_Quest_C");
static_assert(offsetof(UBQ01_TerrorWolf_Quest_C, UberGraphFrame) == 0x000170, "Member 'UBQ01_TerrorWolf_Quest_C::UberGraphFrame' has a wrong offset!");

}

