#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BQ10_Imp_Quest

#include "Basic.hpp"

#include "BQ10_Imp_Quest_classes.hpp"
#include "BQ10_Imp_Quest_parameters.hpp"


namespace SDK
{

// Function BQ10_Imp_Quest.BQ10_Imp_Quest_C.ExecuteUbergraph_BQ10_Imp_Quest
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBQ10_Imp_Quest_C::ExecuteUbergraph_BQ10_Imp_Quest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BQ10_Imp_Quest_C", "ExecuteUbergraph_BQ10_Imp_Quest");

	Params::BQ10_Imp_Quest_C_ExecuteUbergraph_BQ10_Imp_Quest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BQ10_Imp_Quest.BQ10_Imp_Quest_C.ConstructQuestObjectives
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBQ10_Imp_Quest_C::ConstructQuestObjectives()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BQ10_Imp_Quest_C", "ConstructQuestObjectives");

	UObject::ProcessEvent(Func, nullptr);
}

}

