#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BQ12_FrostMage_Quest

#include "Basic.hpp"

#include "BQ12_FrostMage_Quest_classes.hpp"
#include "BQ12_FrostMage_Quest_parameters.hpp"


namespace SDK
{

// Function BQ12_FrostMage_Quest.BQ12_FrostMage_Quest_C.ConstructQuestObjectives
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBQ12_FrostMage_Quest_C::ConstructQuestObjectives()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BQ12_FrostMage_Quest_C", "ConstructQuestObjectives");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BQ12_FrostMage_Quest.BQ12_FrostMage_Quest_C.ExecuteUbergraph_BQ12_FrostMage_Quest
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBQ12_FrostMage_Quest_C::ExecuteUbergraph_BQ12_FrostMage_Quest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BQ12_FrostMage_Quest_C", "ExecuteUbergraph_BQ12_FrostMage_Quest");

	Params::BQ12_FrostMage_Quest_C_ExecuteUbergraph_BQ12_FrostMage_Quest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

