#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KingPriest_Conversation

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KingPriest_Conversation.KingPriest_Conversation_C
// 0x0008 (0x0230 - 0x0228)
class AKingPriest_Conversation_C final : public AConversationInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_KingPriest_Conversation(int32 EntryPoint);
	void BPOnStartConversation(class FName ConversationName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KingPriest_Conversation_C">();
	}
	static class AKingPriest_Conversation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AKingPriest_Conversation_C>();
	}
};
static_assert(alignof(AKingPriest_Conversation_C) == 0x000008, "Wrong alignment on AKingPriest_Conversation_C");
static_assert(sizeof(AKingPriest_Conversation_C) == 0x000230, "Wrong size on AKingPriest_Conversation_C");
static_assert(offsetof(AKingPriest_Conversation_C, UberGraphFrame) == 0x000228, "Member 'AKingPriest_Conversation_C::UberGraphFrame' has a wrong offset!");

}

