#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MQ01_WitchHunt_Quest

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MQ01_WitchHunt_Quest.MQ01_WitchHunt_Quest_C
// 0x0010 (0x0180 - 0x0170)
class UMQ01_WitchHunt_Quest_C final : public UManQuest
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0170(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UManQuestObjective*                     SwampObj2;                                         // 0x0178(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_MQ01_WitchHunt_Quest(int32 EntryPoint);
	void PreObjectileComplete(class UManQuestObjective* Objectile);
	void ConstructQuestObjectives();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MQ01_WitchHunt_Quest_C">();
	}
	static class UMQ01_WitchHunt_Quest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMQ01_WitchHunt_Quest_C>();
	}
};
static_assert(alignof(UMQ01_WitchHunt_Quest_C) == 0x000008, "Wrong alignment on UMQ01_WitchHunt_Quest_C");
static_assert(sizeof(UMQ01_WitchHunt_Quest_C) == 0x000180, "Wrong size on UMQ01_WitchHunt_Quest_C");
static_assert(offsetof(UMQ01_WitchHunt_Quest_C, UberGraphFrame) == 0x000170, "Member 'UMQ01_WitchHunt_Quest_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UMQ01_WitchHunt_Quest_C, SwampObj2) == 0x000178, "Member 'UMQ01_WitchHunt_Quest_C::SwampObj2' has a wrong offset!");

}

