#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Rhys_Caravan_Conversation

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "man_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Rhys_Caravan_Conversation.Rhys_Caravan_Conversation_C
// 0x0010 (0x0238 - 0x0228)
class ARhys_Caravan_Conversation_C final : public AConversationInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_OccultistNPC_C*                     Rhys;                                              // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BPOnStartConversation(class FName ConversationName);
	void Hub();
	void Questions();
	void Trade();
	void GoatQuest();
	void GoatTurnIn();
	void StudyQuest();
	void StudyTurnIn();
	void MagicBook();
	void MagicBookDone();
	void ClearText();
	void asd();
	void ReceiveBeginPlay();
	void Intro();
	void DragonMessage();
	void ExecuteUbergraph_Rhys_Caravan_Conversation(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Rhys_Caravan_Conversation_C">();
	}
	static class ARhys_Caravan_Conversation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARhys_Caravan_Conversation_C>();
	}
};
static_assert(alignof(ARhys_Caravan_Conversation_C) == 0x000008, "Wrong alignment on ARhys_Caravan_Conversation_C");
static_assert(sizeof(ARhys_Caravan_Conversation_C) == 0x000238, "Wrong size on ARhys_Caravan_Conversation_C");
static_assert(offsetof(ARhys_Caravan_Conversation_C, UberGraphFrame) == 0x000228, "Member 'ARhys_Caravan_Conversation_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ARhys_Caravan_Conversation_C, Rhys) == 0x000230, "Member 'ARhys_Caravan_Conversation_C::Rhys' has a wrong offset!");

}

